---
- name: Warn if vault_newrelic_license is not defined
  debug:
    msg: |
      Skipping New Relic tasks. vault_newrelic_license is not set.
  when: vault_newrelic_license is not defined

- include: install.yml
  when: vault_newrelic_license is defined
- include: ini.yml
  when: vault_newrelic_license is defined
